version: '2'
services:
    anacredit-app:
        image: anacredit
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://anacredit-postgresql:5432/anacredit
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=anacredit-elasticsearch:9300
        ports:
            - 8080:8080
    anacredit-postgresql:
        extends:
            file: postgresql.yml
            service: anacredit-postgresql
    anacredit-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: anacredit-elasticsearch
